version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: minigram-postgres-stage2
    environment:
      POSTGRES_DB: minigram
      POSTGRES_USER: minigram_user
      POSTGRES_PASSWORD: minigram_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minigram_user -d minigram"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: 
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "max_connections=200"

  redis:
    image: redis:7-alpine
    container_name: minigram-redis-stage2
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: